[package]
name = "matchbook"
version = "0.1.0"
authors = ["Will Johnston <wbjohnston@gmail.com>"]
edition = "2018"

[features]

[dependencies]
engine = { path = "./engine" }
clap = "2.33"
failure = "0.1"
serde_json = "1.0"
serde = "1.0"
log = "0.4"
